# Generated by Django 4.0.4 on 2022-05-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
